title: Choi_soliloquy
name: "Yeonjun's Study Blog"
author: Yeonjun Choi
instagram_username: choi_soliloquy
baseurl: ""
description: Document my learning notes.
profile_url: "http://choipostech.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-ZBP54F74E0"
    anonymize_ip         : # true, false (default)
