title: Choi_soliloquy
name: "Yeonjun's Study Blog"
author: Yeonjun Choi
instagram_username: choi_soliloquy
baseurl: ""
description: Document my learning notes.
profile_url: "http://choipostech.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
